/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.seguridad;


import Modelo.seguridad.AsingnacionPerfilDAO;
import Modelo.seguridad.RellenarCombos;
import Controlador.seguridad.AsignacionPerfil;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import Controlador.seguridad.Bitacora;
import Controlador.seguridad.UsuarioConectado;
import Modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author visitante
 */
public class AsignacionUsuarioPerfil extends javax.swing.JInternalFrame {
int APLICACION=101;

    
   /* 
    }
    

   
    }

    public void buscarVendedor() {
        Aplicacion aplicacionAConsultar = new Aplicacion();
        AplicacionDAO aplicacionDAO = new AplicacionDAO();
        aplicacionAConsultar.setId_aplicacion(Integer.parseInt(txtbuscado.getText()));
        aplicacionAConsultar = aplicacionDAO.query(aplicacionAConsultar);
        txtNombre.setText(aplicacionAConsultar.getNombre_aplicacion());
        txtEstatus.setText(aplicacionAConsultar.getEstatus_aplicacion());
        int resultadoBitacora=0;
        Bitacora bitacoraRegistro = new Bitacora();
        resultadoBitacora = bitacoraRegistro.setIngresarBitacora(UsuarioConectado.getIdUsuario(), APLICACION,  "Buscar Datos Aplicacion");    
   
    }
*/
 public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
       
        modelo.addColumn("id Usuario");
        modelo.addColumn("ID Perfil");
        AsingnacionPerfilDAO asingnacionPerfilDAO = new AsingnacionPerfilDAO();
        List<AsignacionPerfil> asignacionPerfiles = asingnacionPerfilDAO.select();
        tablaUsuarioAplicacion.setModel(modelo);
        String[] dato = new String[3];
        for (int i = 0; i < asignacionPerfiles.size(); i++) {
            dato[0] = Integer.toString(asignacionPerfiles.get(i).getId_usuario());
            //dato[0] = aulas.get(i).getId_aplicacion();
            dato[1] = Integer.toString(asignacionPerfiles.get(i).getId_perfil());
         
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
 }
 
 private void insertarAsignacion(int idUsuario, int idPerfil) throws SQLException {
    String sql = "INSERT INTO usuario_perfil (id_usuario, id_perfil) VALUES (?, ?)";
    
    try (Connection conexion = Conexion.getConnection();
         PreparedStatement pst = conexion.prepareStatement(sql)) {
        
        pst.setInt(1, idUsuario);
        pst.setInt(2, idPerfil);
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Asignación guardada exitosamente");
    }
}
 
    public AsignacionUsuarioPerfil() {
       
        
        
        initComponents();
        llenadoDeTablas();
     
      RellenarCombos re = new RellenarCombos();
   
        
        
    try {
        re.RellenarComboBox("usuario", "username", cboUsuario);
        re.RellenarComboBox("perfiles", "nombre_perfil", cboPerfil);
    } catch (SQLException ex) {
        Logger.getLogger(AsignacionUsuarioPerfil.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    

    
    }





  
    









    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboUsuario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboPerfil = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarioAplicacion = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cboPerfilesAsignados = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarioAplicacion1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuario Aplicacion");
        setVisible(true);

        jLabel1.setText("Usuario");

        cboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Perfil");

        cboPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPerfilActionPerformed(evt);
            }
        });

        tablaUsuarioAplicacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaUsuarioAplicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_aplicacion", "nombre_aplicacion", "estatus_aplicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarioAplicacion);

        btnAgregar.setText("Asignar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Retirar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar Usuario");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaUsuarioAplicacion1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaUsuarioAplicacion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_aplicacion", "nombre_aplicacion", "estatus_aplicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaUsuarioAplicacion1);

        jLabel3.setText("PERFILES DISPONIBLES DEL USUARIO");

        jLabel4.setText("ASIGNACIÒN DE PERFIL A USUARIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(cboPerfilesAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPerfilesAsignados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar)
                    .addComponent(cboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cboUsuarioActionPerformed

    private void cboPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPerfilActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cboPerfilActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        try {
        // 1. Obtener nombres seleccionados
        String nombreUsuario = cboUsuario.getSelectedItem().toString();
        String nombrePerfil = cboPerfil.getSelectedItem().toString();
        
        // 2. Validar que no sean la opción por defecto
        if ("Seleccione una opción".equals(nombreUsuario) || "Seleccione una opción".equals(nombrePerfil)) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario y un perfil válidos");
            return;
        }
        
        // 3. Obtener IDs correspondientes
        RellenarCombos re = new RellenarCombos();
        int idUsuario = re.obtenerIdPorNombre("usuario", "username", "id_usuario", nombreUsuario);
        int idPerfil = re.obtenerIdPorNombre("perfiles", "nombre_perfil", "id_perfil", nombrePerfil);
        
        // 4. Insertar en la tabla usuario_perfil
        insertarAsignacion(idUsuario, idPerfil);
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        
         try {
        // 1. Obtener nombres seleccionados
        String nombreUsuario = cboUsuario.getSelectedItem().toString();
        String nombrePerfil = cboPerfil.getSelectedItem().toString();
        
        // 2. Validar selección
        if ("Seleccione una opción".equals(nombreUsuario) || "Seleccione una opción".equals(nombrePerfil)) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario y un perfil válidos");
            return;
        }
        
        // 3. Obtener IDs
        RellenarCombos re = new RellenarCombos();
        int idUsuario = re.obtenerIdPorNombre("usuario", "username", "id_usuario", nombreUsuario);
        int idPerfil = re.obtenerIdPorNombre("perfiles", "nombre_perfil", "id_perfil", nombrePerfil);
        
        // 4. Eliminar asignación
        if (re.eliminarAsignacion(idUsuario, idPerfil)) {
            JOptionPane.showMessageDialog(null, "Asignación retirada correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "La asignación no existe", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Obtener nombre del usuario seleccionado
        String nombreUsuario = cboUsuario.getSelectedItem().toString();
        
        // 2. Validar que no sea la opción por defecto
        if ("Perfiles de usuario son".equals(nombreUsuario)) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario válido");
            return;
        }
        
        // 3. Obtener id_usuario
        RellenarCombos re = new RellenarCombos();
        int idUsuario = re.obtenerIdPorNombre("usuario", "username", "id_usuario", nombreUsuario);
        
        // 4. Cargar perfiles asignados en el nuevo ComboBox
        re.cargarPerfilesAsignados(idUsuario, cboPerfilesAsignados); // Asume que tienes un JComboBox llamado cboPerfilesAsignados
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboPerfil;
    private javax.swing.JComboBox<String> cboPerfilesAsignados;
    private javax.swing.JComboBox<String> cboUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaUsuarioAplicacion;
    private javax.swing.JTable tablaUsuarioAplicacion1;
    // End of variables declaration//GEN-END:variables
}
